name = "Create PROPERLY"
author = "TuxeBro"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41419e02ec5ed75a178130bd5aaf7e9c77d05f2564e2386b9f56d0e073d4fd1b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
